[build]
  command = "npm run generate-git-info && npm run build"
  publish = "/"

[build.environment]
  NODE_VERSION = "22"

# Proxy API requests to avoid CORS issues
[[redirects]]
  from = "/api/swpublisher/*"
  to = "https://swpublisher.entu.eu/:splat"
  status = 200
  force = true
